### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by slanska** [szieke/embLua#1]
Subj, essentially. Thanks!

**Comment by szieke** [comment]
Hi slanka,
I don't understand your comment. What are you trying to say?

**Comment by slanska** [comment]
Hi @szieke , I apologize for not being very clear. What I meant is that whether this library is tested in the field, i.e. whether can it be considered for a real project. I am interested to check combination of FreeRTOS and embedded Lua for certain tasks (for example, UI or web traffic processing). Thanks a lot!

**Comment by szieke** [comment]
Hi slanska,

to be honest I had some time at work and created embLua (and tested it with a MSP430 and a Renesas project) because I thought scripting functionality could be useful in a future project. But I never had the possibility to use it in a 'real project'.

**Comment by slanska** [comment]
Thank you for the reply! I will give it a try and see.
