### ISSUE TITLE
Trying to compile with XC8 gives Conflicting Declaration error

### ISSUE THREAD

**Issue by RozeDoyanawa** [szieke/embLua#2]
Hi, 
I just downloaded this to try running it on a PIC18 micro. However, I cannot compile it because of:
lua/ltable.h:50:: error: (1098) conflicting declarations for variable "_luaH_set" (lua/ltable.h:50)

It seems the compiler generates two separate call-graphs; one that contains ltable + lcode, and one that contains lapi + llex, both of which requires ltable, but they get their own "definitions", so when xc8-cc tries to link, it finds two instances of the same method:

Following is a excerpt from the object files generated.
https://pastebin.com/jptRe74H

I'm assuming this is because of the weird cyclic dependency between llimits and the rest.   
Any suggestions on how to fix?

**Comment by szieke** [comment]
I wish I could help you. But no, I have no clue how to fix this.
